timeout: 600s

substitutions:
  _USE_CACHE: "true"
  _APP_NAME: app
  _IMAGE_PREFIX: gst-webrtc
  _IMAGE_TAG: latest

tags:
  - gst-webrtc-app-image

###
# Images to be pushed
###
images: [
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-${_APP_NAME}:${_IMAGE_TAG}',
    'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-${_APP_NAME}:latest',
]

steps:
###
# App Image
###
- name: 'gcr.io/cloud-builders/docker'
  id: image-pull
  entrypoint: 'bash'
  args: ["-c", "if [[ '${_USE_CACHE}' == 'true' ]]; then (docker pull gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-${_APP_NAME}:latest || exit 0); fi"]
  waitFor: ["-"]
- name: 'gcr.io/cloud-builders/gcloud'
  id: fetch-artifacts
  entrypoint: 'bash'
  args:
    - -exc
    - |
      gsutil cp gs://${PROJECT_ID}-vdi/selkies-gstreamer/selkies-gstreamer-latest.tgz .
- name: 'gcr.io/cloud-builders/docker'
  id: image
  args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-${_APP_NAME}:${_IMAGE_TAG}',
            '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-${_APP_NAME}:latest',
            '.'
        ]
  waitFor:
    - image-pull
    - fetch-artifacts
- name: 'gcr.io/cloud-builders/docker'
  id: image-tags
  args: [
            'tag',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-${_APP_NAME}:${_IMAGE_TAG}',
            'gcr.io/${PROJECT_ID}/${_IMAGE_PREFIX}-${_APP_NAME}:latest',
        ]
  waitFor:
    - image
