name: Build & publish all images

on: workflow_dispatch

jobs:
  ###
  # Coturn image
  ###
  build_and_publish_addons_coturn:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: addons/coturn
        push: true
        tags: ghcr.io/selkies-project/selkies-gstreamer/coturn:latest
        cache-from: type=registry,ref=selkies-project/selkies-gstreamer/coturn:buildcache
        cache-to: type=registry,ref=selkies-project/selkies-gstreamer/coturn:buildcache,mode=max

  ###
  # Coturn Web image
  ###
#  build_and_publish_addons_coturn-web:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: ./.github/actions/build_and_publish_image
#      with:
#        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
#        github_username: ${{ github.actor }}
#        image_source_directory: addons/coturn-web
#        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/coturn-web:latest

  ###
  # Gstreamer image
  ###
#  build_and_publish_addons_gstreamer:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: ./.github/actions/build_and_publish_image
#      with:
#        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
#        github_username: ${{ github.actor }}
#        image_source_directory: addons/gstreamer
#        image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/gstreamer:latest
